//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Devoluciones
    {
        public int IdDevolucion { get; set; }
        public int IdVenta { get; set; }
        public int IDCliente { get; set; }
        public System.DateTime FechaDevolucion { get; set; }
        public double CantidadProducto { get; set; }
        public int IdUsuario { get; set; }
    
        public virtual Tab_Clientes Tab_Clientes { get; set; }
        public virtual Tab_Usuarios Tab_Usuarios { get; set; }
        public virtual Tab_Venta Tab_Venta { get; set; }
    }
}
