//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Bitacora_Movimientos
    {
        public int codigo_movimiento_usuario { get; set; }
        public System.DateTime fecha_hora_movimiento { get; set; }
        public string tipo_movimiento { get; set; }
        public string modulo { get; set; }
        public Nullable<int> Id_Usuario { get; set; }
    
        public virtual Tab_Usuarios Tab_Usuarios { get; set; }
    }
}
