//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Permisos
    {
        public int ID { get; set; }
        public string Modulo { get; set; }
        public string Accion { get; set; }
        public int Id_Rol { get; set; }
    
        public virtual Tab_Roles Tab_Roles { get; set; }
    }
}
